mytestkey=This value is from DEV properties file

# PayPal credentials - reading from AWS Secrets Manager
#paypal.client.id=<READING FROM AWS SECRETS MANAGER>
#paypal.client.secret=<READING FROM AWS SECRETS MANAGER>

# PayPal URLs
paypal.oath.url=https://api-m.sandbox.paypal.com/v1/oauth2/token
paypal.create.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders
paypal.capture.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders/{orderId}/capture

# Redis - AWS ElastiCache
spring.data.redis.cluster.nodes=clustercfg.paypal-access-token.4rlahf.aps1.cache.amazonaws.com:6379
spring.data.redis.ssl.enabled=true

# AWS Secrets Manager
spring.config.import=aws-secretsmanager:dev/paypal-provider-service