mytestkey=This value is from LOCAL properties file

# PayPal OAuth endpoint - public URL
paypal.oath.url=https://api-m.sandbox.paypal.com/v1/oauth2/token

paypal.create.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders
paypal.capture.order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders/{orderId}/capture

# These reference .env
paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}